mixed-port: 10801
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: true
external-controller: 0.0.0.0:9093
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  nameserver:
    - 114.114.114.114
    - https://doh.pub/dns-query
  fallback:
    - tls://1.1.1.1
    - https://dns.google/dns-query
proxies:
  - name: ç¤ºä¾‹VMessèŠ‚ç‚¹
    type: vmess
    server: example.com
    port: 443
    uuid: your-uuid
    alterId: 0
    cipher: auto
    tls: true
    network: ws
  - name: ç¤ºä¾‹TrojanèŠ‚ç‚¹
    type: trojan
    server: example.com
    port: 443
    password: your-password
    sni: example.com
    udp: true
proxy-groups:
  - name: ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
    type: select
    proxies:
      - ç¤ºä¾‹VMessèŠ‚ç‚¹
      - ç¤ºä¾‹TrojanèŠ‚ç‚¹
      - DIRECT
  - name: ğŸ”° è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - ç¤ºä¾‹SSèŠ‚ç‚¹
      - ç¤ºä¾‹VMessèŠ‚ç‚¹
      - ç¤ºä¾‹TrojanèŠ‚ç‚¹
  - name: ğŸ“² ç”µæŠ¥æ¶ˆæ¯
    type: select
    proxies:
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ”° è‡ªåŠ¨é€‰æ‹©
  - name: ğŸ¯ å…¨çƒç›´è¿
    type: select
    proxies:
      - DIRECT
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
  - name: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
    type: select
    proxies:
      - REJECT
      - DIRECT
rules:
  - DOMAIN-SUFFIX,google.com,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
  - DOMAIN-KEYWORD,google,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
  - DOMAIN,google.com,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
  - DOMAIN-SUFFIX,telegram.org,ğŸ“² ç”µæŠ¥æ¶ˆæ¯
  - IP-CIDR,127.0.0.0/8,ğŸ¯ å…¨çƒç›´è¿
  - GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿
  - MATCH,ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
external-ui: ''
